version: '2'
services:
  tfenewbackend-app:
    image: tfenewbackend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://tfenewbackend-mysql:3306/tfenewbackend?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  tfenewbackend-mysql:
    extends:
      file: mysql.yml
      service: tfenewbackend-mysql
